#!/usr/bin/env php
<?php

if (count($argv) < 4) {
    print usage();
    exit(1);
}

$hosts_template_path = $argv[1];
$destination_hosts_path = $argv[2];

if (!file_exists($hosts_template_path)) {
    print 'Hosts template file is missing or is not readable';
    exit(1);
}

if (!file_exists(dirname($destination_hosts_path))) {
    print 'Destination hosts file directory is missing or is not readable';
    exit(1);
}

$template_contents = file_get_contents($hosts_template_path);

$hostnames = array_slice($argv, 3);

$substitutions = array(
    'hostnames' => implode(' ', $hostnames)
);

$config = $template_contents;
foreach ($substitutions as $find => $replace) {
    $config = str_replace('{{' . $find . '}}', $replace, $config);
}

#var_dump($config);

file_put_contents($destination_hosts_path, $config);

exit;

function usage() {
    return 'configure-hosts-file.php <hosts_template_path> <destination_hosts_path> <full_qualified_hostname> [<host_alias_1> <host_alias_2> ... host_alias_N]';
}
