#!/bin/bash

# Crash on any error
set -e

# Load LXC defaults
if [ -r /etc/default/lxc ]; then
    . /etc/default/lxc
fi

profile_download_url=""
profile_download_server="http://image.rainmaker.localdev"

lxc_cache_base="/var/cache/lxc/rainmaker/project-branch"

# Download the rootfs archive if not present in the download cache
download() {
	url=$1
	path=$2
	mkdir -p `dirname $path`
	wget --progress=bar -O $path $url
}

# The install function installs the minimal operating system in the LXC
install() {
	profile_path=$1
    rootfs_dir=$2
	tar -C $rootfs_dir -xzf $profile_path
}

# Set up the path option
options=$(getopt -o n:p: -l path:,name:,rootfs:,profile:,version: -- "$@")

if [ $? -ne 0 ]; then
    exit 1
fi

eval set -- "$options"

# Fetch command line parameters
while true; do
    case "$1" in
        -p|--path)      path=$2; shift 2;;
        -n|--name)      name=$2; shift 2;;
        --rootfs)       rootfs=$2; shift 2;;
        --profile)      profile=$2; shift 2;;
        --version)      version=$2; shift 2;;
        --)             shift 1; break ;;
        *)              break ;;
    esac
done

if [ -z "$path" ]; then
    echo "'path' parameter is required"
    exit 1
fi

if [ -z "$profile" ]; then
    profile="drupal-classic"
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script should be run as 'root'"
    exit 1
fi

# detect rootfs
config="$path/config"
# if $rootfs exists here, it was passed in with --rootfs
if [ -z "$rootfs" ]; then
    if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
        rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $config)
    else
        rootfs=$path/rootfs
    fi
fi

profile_download_base_url="$profile_download_server/rootfs/project-branch/$profile"
profile_latest_url="$profile_download_server/rootfs/project-branch/$profile/latest"

if [ -z "$version" ]; then
    version=`curl -s $profile_latest_url`
fi

major=`echo $version | cut -d'.' -f1`
profile_downlold_url="$profile_download_base_url/$major/project-branch-$profile-$version.tgz"
lxc_cache_path="$lxc_cache_base/$major/project-branch-$profile-$version.tgz"

if [ ! -f "$lxc_cache_path" ]; then
	download $profile_downlold_url $lxc_cache_path
fi

install $lxc_cache_path $rootfs


