VAGRANTFILE_API_VERSION = "2"

BOX      = "ubuntu/trusty64"
URL      = "https://vagrantcloud.com/ubuntu/boxes/trusty64"
RAM      = "512"
VBOX_GUI = true

$script = <<SCRIPT
wget "https://gist.githubusercontent.com/adam-dg/8f41b779ae657aca30eb/raw/cf3d7abe748dd670f36e24988d789245c8fffef0/prepare-vagrant-box.sh" -O /etc/prep.sh
chmod u+x /etc/prep.sh
/etc/prep.sh | tee /etc/prep.sh.log
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX

  config.vm.provider "virtualbox" do |vb|
    vb.gui = VBOX_GUI
    vb.customize ["modifyvm", :id, "--memory", RAM]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: $script

end
